### ISSUE TITLE
I'm asking for a video tutorial on how to do it all

### ISSUE THREAD

**Issue by pythonpychar** [N0rz3/Phunter#18]
Your instructions that you wrote are not very clear And I didn’t succeed and I want you to make a video tutorial so that I can do everything for the rest
If you have time, please make a video

If anything, I communicate through Google translator

**Comment by D4m13n-contrib** [comment]
Hi,

I tried this application recently and I didn't have any problems with instructions to execute it, I think a video tutorial about how to run it is a little bit overkill, it is a very simple application (without offense @N0rz3 ;)).

What instructions did you not understand ? Installation ? Options ?

**Comment by pythonpychar** [comment]
1. I didn’t understand this. When you need to enter the setting, where in
cmd python git 2. how to enter commands correctly and why the phunter.py
file does not start 3. Just a question: is it compatible with Windows 11?

пт, 8 нояб. 2024 г., 19:11 D4m13n-contrib ***@***.***>:

**Comment by pythonpychar** [comment]
If anything, I’m from Kyrgyzstan, I don’t understand anything about
programming and I just want to scare my classmate)

пт, 8 нояб. 2024 г., 21:35 Амир Джумалиев ***@***.***>:

**Comment by pythonpychar** [comment]
Maybe I can download another program but he Useful

пт, 8 нояб. 2024 г., 21:38 Амир Джумалиев ***@***.***>:

**Comment by D4m13n-contrib** [comment]
1.There is no settings to configure for the application, but if your question is about the installation (`git clone`, `pip install`) you can take a look for [https://learn.microsoft.com/en-us/windows/python/beginners](https://learn.microsoft.com/en-us/windows/python/beginners) or
[https://nerdschalk.com/how-to-install-pip-on-windows-11/](https://nerdschalk.com/how-to-install-pip-on-windows-11/).
When the application is installed you can test it by open a terminal, go (with command: `cd`) to the folder of the application and type `python phunter.py --help` to see if it works.

2. Do not execute phunter.py by clicking to this file directly, you must use a terminal command line.

3. I don't know if it works on Windows, i only tried with Linux (Ubuntu).

I think your problem is not "How to use this application?", but also more generally "How to execute a Python application on Windows 11 ?". For that I recommend you to search (Ecosia, Google, etc.) generic tuto/blog/video/... about Python application on Windows.

**Comment by pythonpychar** [comment]
Okay, thanks, and now I'm going to the amusement park and after that I'll
check, God willing, that it works, otherwise I'll be afraid of the
computer:)

пт, 8 нояб. 2024 г., 22:08 D4m13n-contrib ***@***.***>:

**Comment by pythonpychar** [comment]
And this is the first time I've spoken to a foreigner, even if it's by
mail))))

сб, 9 нояб. 2024 г., 09:14 Амир Джумалиев ***@***.***>:

**Comment by pythonpychar** [comment]
> 1. Для приложения нет настроек для настройки, но если у вас вопрос об установке ( `git clone`, `pip install`), вы можете взглянуть на https://learn.microsoft.com/en-us/windows/python/beginners или 
>    https://nerdschalk.com/how-to-install-pip-on-windows-11/ . 
>    Когда приложение установлено, вы можете протестировать его, открыв терминал, перейдя (с помощью команды: `cd`) в папку приложения и введя , `python phunter.py --help`чтобы проверить, работает ли оно.
> 2. Не запускайте phunter.py, щелкая по этому файлу напрямую, необходимо использовать командную строку терминала.
> 3. Я не знаю, работает ли это на Windows, я пробовал только на Linux (Ubuntu).
> 
> Я думаю, что ваша проблема не в том, «Как использовать это приложение?», а в более общем смысле «Как выполнить приложение Python в Windows 11?». Для этого я рекомендую вам поискать (Ecosia, Google и т. д.) общие руководства/блоги/видео/... о приложении Python в Windows.

Thank you! all works
